name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/HelloWorld/HelloWorld.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HelloWorld/HelloWorld.csproj
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      run: dotnet test --verbosity normal ./src/HelloWorld.Tests/HelloWorld.Tests.csproj
