name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/Provisioning/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'src/Provisioning/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/HelloWorld/HelloWorld.csproj

    - name: Build
      run: dotnet build --no-restore ./src/HelloWorld/HelloWorld.csproj --configuration Release

    - name: Publish
      run: dotnet publish ./src/HelloWorld/HelloWorld.csproj -c Release -o ${{env.DOTNET_ROOT}}/DemoApp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: DemoApp
        path: ${{env.DOTNET_ROOT}}/DemoApp
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Test
      run: dotnet test --verbosity normal ./src/HelloWorld.Tests/HelloWorld.Tests.csproj

  deploy:
      runs-on: ubuntu-latest
      needs: tests
      environment:
        name: 'production'
        url: ${{ steps.deploywebapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: DemoApp

        - name: Login via Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy web app
          id: deploywebapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: demoAppMJ12345
            package: DemoApp

        - name: az cli logout
          run: az logout